"""add ats fields to companies

Revision ID: e344ca293b51
Revises: 001
Create Date: 2026-03-07 12:47:50.616692
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e344ca293b51'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('ats_platform', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('ats_slug', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'email')
    op.drop_column('companies', 'ats_slug')
    op.drop_column('companies', 'ats_platform')
    # ### end Alembic commands ###
